# 配置文件
debug: true

server:
  port: 8080

spring:
  # 当前配置环境
  profiles:
    active: dev
  # 设置国际化资源文件基础名.默认为 message.properties,放在资源根路径下
  messages:
    basename: resources.i18n.message
---
# 开发环境信息
spring:
  profiles: dev
  resources:
    # 静态资源位置
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  thymeleaf:
    cache: false
  mvc:
    date-format:
  # 数据库信息
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库启动默认SQL动作
#    schema:
#      - classpath:db\\department.sql
#      - classpath:db\\department.sql
#    initialization-mode: always
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

# 日志信息,在不配置日志输出时,默认只将日志输出到控制台
logging:
  # 不同位置的日志级别
  level:
    top.jionjion.demo.log: warn
    top.jionjion.demo.config: info
  # 当前项目下生成日志目录.文件名spring.log
  path: log
  # 指定生成的文件名及位置
  file: F:\\JAVA_WorkSpace\\demo\\log\\demo.log
  # 控制台,文件日志格式
#  pattern:
#    console:
#    file:

# 静态资源的配置


# 自定义配置信息
demo:
  enable: true
  author: "Mr.Jion"
  date: 2019-07-21
  info: {version: 1.0, builder: Dev}
  helpers: [Jion, AtGuiGu]
